from datetime import datetime

from infra.registry_loader import get_loader


_MONTH_ABB = {
    1: "JAN",
    2: "FEB",
    3: "MAR",
    4: "APR",
    5: "MAY",
    6: "JUN",
    7: "JUL",
    8: "AUG",
    9: "SEP",
    10: "OCT",
    11: "NOV",
    12: "DEC",
}


def _fmt(v, width=14):
    if isinstance(v, int):
        return str(v).rjust(width)
    if abs(v) >= 1e5 or (abs(v) < 1e-3 and v != 0):
        return f"{v:.6E}".rjust(width)
    return f"{v:.6g}".rjust(width)


def _get_val(obj):
    if obj is None:
        return None
    if isinstance(obj, dict):
        if obj.get("type") == "scalar":
            return obj["value"]
        if obj.get("type") == "array":
            return obj["values"]
    return obj


def _compress_array(vals):
    if not vals:
        return ""
    parts = []
    i = 0
    while i < len(vals):
        v = vals[i]
        count = 1
        while i + count < len(vals) and vals[i + count] == v:
            count += 1
        if count > 1:
            parts.append(f"{count}*{_fmt(v).strip()}")
        else:
            parts.append(_fmt(v).strip())
        i += count
    chunks = []
    chunk = []
    for p in parts:
        chunk.append(p)
        if len(chunk) >= 8:
            chunks.append("  " + "  ".join(chunk))
            chunk = []
    if chunk:
        chunks.append("  " + "  ".join(chunk))
    return "\n".join(chunks)


def _write_array_petrel(lines, keyword, obj, trailing_slash=True):
    if obj is None:
        return
    val = _get_val(obj)
    if val is None:
        return
    lines.append(keyword)
    if isinstance(val, list):
        body = _compress_array(val)
        lines.append(body + "  /" if trailing_slash else body)
    else:
        lines.append(f"  {_fmt(val).strip()} /" if trailing_slash else f"  {_fmt(val).strip()}")


def _write_table_slash(lines, keyword, tbl, columns=None):
    if not tbl or not tbl.get("rows"):
        return
    cols = columns or tbl.get("columns", [])
    lines.append(keyword)
    if cols:
        lines.append("-- " + "  ".join(f"{c:>10}" for c in cols))
    for row in tbl["rows"]:
        lines.append("  " + "  ".join(_fmt(v) for v in row) + "  /")
    lines.append("/")


class PetrelWriter:
    def __init__(self):
        self._rl = get_loader()
        self._gen_cfg = self._rl.petrel_gen_config()

    def generate(self, data):
        lines = []
        meta = data.get("meta", {})
        grid = data.get("grid", {})
        reservoir = data.get("reservoir", {})
        fluid = data.get("fluid", {})
        rockfluid = data.get("rockfluid", {})
        initial = data.get("initial", {})
        wells = data.get("wells", [])
        timeline_events = data.get("timeline_events", [])
        lines += [
            "-- Generated by UDA Middle Layer",
            f"-- Source: {meta.get('source_file', 'unknown')}",
            f"-- Date:   {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "",
        ]
        self._write_runspec(lines, meta, grid, wells)
        self._write_grid_section(lines, grid, reservoir)
        self._write_props(lines, fluid, rockfluid)
        self._write_solution(lines, initial)
        self._write_summary(lines)
        self._write_schedule(lines, wells, meta, timeline_events)
        self._write_unparsed_blocks(lines, data.get("unparsed_blocks", []))
        lines.append("END")
        return "\n".join(lines) + "\n"

    def _write_runspec(self, lines, meta, grid, wells):
        lines += ["RUNSPEC", ""]
        start = meta.get("start_date", "")
        if start:
            parts = start.split("-")
            if len(parts) == 3:
                mon_str = _MONTH_ABB.get(int(parts[1]), "JAN")
                lines.extend(["START", f"  {int(parts[2])} '{mon_str}' {parts[0]} /", ""])
        ni = grid.get("ni", 1)
        nj = grid.get("nj", 1)
        nk = grid.get("nk", 1)
        lines += ["DIMENS", f"  {ni}  {nj}  {nk} /", "", "OIL", "WATER", "GAS", "DISGAS", ""]
        unit = meta.get("unit_system", "field").upper()
        lines += [unit, ""]
        nwells = max(len(wells), 1)
        nconns = sum(len(w.get("perforations", [])) for w in wells) or nk
        lines += ["WELLDIMS", f"  {nwells}  {nconns}  1  {nwells} /", "", "TABDIMS", "  1 /", ""]

    def _write_grid_section(self, lines, grid, reservoir):
        lines += ["GRID", ""]
        gt = grid.get("grid_type", "CART").upper()
        if gt == "RADIAL":
            lines.extend(["RADIAL", ""])
            inrad = _get_val(grid.get("inrad"))
            if inrad is not None:
                lines.extend(["INRAD", f"  {_fmt(inrad).strip()} /", ""])
            drv_obj = grid.get("di") or grid.get("drv")
            if drv_obj:
                _write_array_petrel(lines, "DRV", drv_obj)
                lines.append("")
            dtheta_obj = grid.get("dj") or grid.get("dtheta")
            if dtheta_obj:
                _write_array_petrel(lines, "DTHETA", dtheta_obj)
                lines.append("")
        else:
            for key, kw in [("di", "DX"), ("dj", "DY"), ("dk", "DZ")]:
                obj = grid.get(key)
                if obj:
                    _write_array_petrel(lines, kw, obj)
                    lines.append("")
        tops_obj = grid.get("tops_ref")
        depth_block = grid.get("depth_ref_block")
        if tops_obj:
            _write_array_petrel(lines, "TOPS", tops_obj)
            lines.append("")
        elif depth_block and isinstance(depth_block, dict):
            ni = grid.get("ni", 1)
            nj = grid.get("nj", 1)
            v = depth_block.get("value", 0)
            lines.extend(["TOPS", f"  {ni * nj}*{_fmt(v).strip()} /", ""])
        for key, kw in {"porosity": "PORO", "perm_i": "PERMX", "perm_j": "PERMY", "perm_k": "PERMZ", "ntg": "NTG"}.items():
            obj = reservoir.get(key)
            if obj:
                _write_array_petrel(lines, kw, obj)
                lines.append("")

    def _write_props(self, lines, fluid, rockfluid):
        lines += ["PROPS", ""]
        pvtw_vals = [_get_val(f) for f in [fluid.get("water_ref_pressure"), fluid.get("water_fvf"), fluid.get("water_compressibility"), fluid.get("water_viscosity"), fluid.get("water_viscosity_coeff")]]
        if any(v is not None for v in pvtw_vals):
            lines.extend(["PVTW", "  " + "  ".join(_fmt(v).strip() if v is not None else "1*" for v in pvtw_vals) + " /", ""])
        od = _get_val(fluid.get("oil_density"))
        wd = _get_val(fluid.get("water_density"))
        gd = _get_val(fluid.get("gas_density"))
        if any(v is not None for v in [od, wd, gd]):
            lines.extend(["DENSITY", "  " + "  ".join(_fmt(v).strip() if v is not None else "1*" for v in [od, wd, gd]) + " /", ""])
        rp = _get_val(fluid.get("rock_ref_pressure") or fluid.get("reservoir", {}).get("rock_ref_pressure"))
        rc = _get_val(fluid.get("rock_compressibility") or fluid.get("reservoir", {}).get("rock_compressibility"))
        if rp is not None and rc is not None:
            lines.extend(["ROCK", f"  {_fmt(rp).strip()}  {_fmt(rc).strip()} /", ""])
        pvto = fluid.get("pvto_table")
        if pvto:
            _write_table_slash(lines, "PVTO", pvto, ["rs", "p", "bo", "viso"])
            lines.append("")
        pvdg = fluid.get("pvdg_table")
        if pvdg:
            _write_table_slash(lines, "PVDG", pvdg, ["p", "bg", "visg"])
            lines.append("")
        self._write_rockfluid(lines, rockfluid)

    def _write_rockfluid(self, lines, rockfluid):
        cfg = self._gen_cfg.get("rockfluid", {})
        wrote = False
        for key, field_cfg in cfg.items():
            tbl = rockfluid.get(key)
            if not tbl or not tbl.get("rows"):
                continue
            kw = field_cfg.get("keyword")
            cols = field_cfg.get("columns")
            if kw and cols:
                _write_table_slash(lines, kw, tbl, cols)
                lines.append("")
                wrote = True
        if not wrote:
            lines.append("-- WARNING: No rock-fluid tables found in JSON")

    def _write_solution(self, lines, initial):
        lines += ["SOLUTION", ""]
        ref_depth = _get_val(initial.get("ref_depth"))
        ref_pres = _get_val(initial.get("ref_pressure"))
        woc = _get_val(initial.get("woc_depth"))
        goc = _get_val(initial.get("goc_depth"))
        if ref_depth is not None and ref_pres is not None:
            woc_str = _fmt(woc).strip() if woc is not None else "0"
            goc_str = _fmt(goc).strip() if goc is not None else "0"
            lines.extend(["EQUIL", f"  {_fmt(ref_depth).strip()}  {_fmt(ref_pres).strip()}  {woc_str}  0  {goc_str}  0 /", ""])
        rsvd = initial.get("rsvd_table")
        if rsvd and rsvd.get("rows"):
            lines.append("RSVD")
            for row in rsvd["rows"]:
                lines.append("  " + "  ".join(_fmt(v) for v in row))
            lines.extend(["/", ""])
        pbvd = initial.get("pbvd_table")
        if pbvd and pbvd.get("rows"):
            lines.append("PBVD")
            for row in pbvd["rows"]:
                lines.append("  " + "  ".join(_fmt(v) for v in row))
            lines.extend(["/", ""])

    def _write_summary(self, lines):
        lines += ["SUMMARY", "", "ALL", "WBHP", "WGOR", ""]

    def _write_schedule(self, lines, wells, meta, timeline_events):
        lines += ["SCHEDULE", ""]
        if wells:
            lines.extend(["WELSPECS", "-- Name   Group  I   J   RefDepth  Phase"])
            for w in wells:
                name = w.get("well_name", "W1")
                group = w.get("well_group", "FIELD")
                ci = w.get("well_i", 1)
                cj = w.get("well_j", 1)
                phase = w.get("phase", "OIL").upper()
                if w.get("well_type", "").upper() == "INJECTOR":
                    phase = w.get("inj_fluid", "GAS") or "GAS"
                lines.append(f"  '{name}'  '{group}'  {ci}  {cj}  1*  {phase} /")
            lines.extend(["/", ""])
        if wells:
            lines.extend(["COMPDAT", "-- Name  I  J  K1 K2  Status  Sat  Trans  Diam"])
            for w in wells:
                name = w.get("well_name", "W1")
                radius = w.get("well_radius")
                diam = (radius * 2.0) if radius else 0.1524
                for p in w.get("perforations", []):
                    status = p.get("status", "OPEN")
                    lines.append(f"  '{name}'  {p['i']}  {p['j']}  {p['k']}  {p['k']}  {status}  1*  1*  {diam:.4f} /")
            lines.extend(["/", ""])
        inj_wells = [w for w in wells if w.get("well_type", "").upper() == "INJECTOR"]
        prod_wells = [w for w in wells if w.get("well_type", "").upper() != "INJECTOR"]
        if inj_wells:
            lines.extend(["WCONINJE", "-- Name  Type  Status  Mode  Rate  Resv  BHP"])
            for w in inj_wells:
                name = w.get("well_name", "W1")
                inj_type = (w.get("inj_fluid") or "GAS").upper()
                rate = w.get("rate_max")
                bhp = w.get("bhp_max")
                rate_str = _fmt(rate).strip() if rate else "1*"
                bhp_str = _fmt(bhp).strip() if bhp else "1*"
                lines.append(f"  '{name}'  {inj_type}  OPEN  RATE  {rate_str}  1*  {bhp_str} /")
            lines.extend(["/", ""])
        if prod_wells:
            lines.extend(["WCONPROD", "-- Name  Status  Mode  Oil  Water  Gas  Liq  Resv  BHP"])
            for w in prod_wells:
                name = w.get("well_name", "W1")
                rate = w.get("rate_max")
                bhp = w.get("bhp_min")
                rate_str = _fmt(rate).strip() if rate else "1*"
                bhp_str = _fmt(bhp).strip() if bhp else "1*"
                lines.append(f"  '{name}'  OPEN  ORAT  {rate_str}  1*  1*  1*  1*  {bhp_str} /")
            lines.extend(["/", ""])
        self._write_dynamic(lines, meta, timeline_events)

    def _write_dynamic(self, lines, meta, timeline_events):
        events = [ev for ev in timeline_events if ev.get("event_type") == "WELL_TARGET_CHANGE"]
        if not events:
            total = meta.get("_total_sim_time", 0.0)
            if total and total > 0:
                lines.extend(["TSTEP", f"  {total:.1f} /", ""])
            return
        events.sort(key=lambda e: float(e.get("absolute_days", 0.0)))
        prev_time = 0.0
        from itertools import groupby
        for t, group in groupby(events, key=lambda e: float(e.get("absolute_days", 0.0))):
            group = list(group)
            dt = t - prev_time
            if dt > 0:
                lines.extend(["TSTEP", f"  {dt:.2f} /", ""])
            for ev in group:
                name = ev.get("well_name", "W1")
                target = ev.get("target", "ORATE")
                val = ev.get("value", 0.0)
                lines.extend(["WELTARG", f"  '{name}'  {target}  {_fmt(val).strip()} /", "/", ""])
            prev_time = t
        total = meta.get("_total_sim_time", prev_time)
        if total > prev_time:
            lines.extend(["TSTEP", f"  {total - prev_time:.2f} /", ""])

    def _write_unparsed_blocks(self, lines, unparsed_blocks):
        if not unparsed_blocks:
            return
        lines.append("-- UNPARSED BLOCKS")
        for blk in unparsed_blocks:
            ln = blk.get("line", "?")
            txt = str(blk.get("text", "")).strip()
            lines.append(f"-- UNPARSED [line {ln}]: {txt}")
