# =============================================================================
# petrel_generator.py  —  通用 JSON dict → Petrel Eclipse .DATA
# 支持：RUNSPEC / GRID / PROPS / SOLUTION / SCHEDULE
# 单位系统：保留原始单位（field 或 metric），不在本文件做换算
# =============================================================================

import json
from pathlib import Path
from datetime import datetime

# ── 工具函数 ──────────────────────────────────────────────────────────────────

def _fmt(v):
    """数值格式化：整数用整数格式，普通小数用 g，极大/极小用科学计数"""
    if isinstance(v, int):
        return str(v)
    if v == 0.0:
        return "0"
    if abs(v) >= 1e-4 and abs(v) < 1e6:
        return f"{v:.10g}"
    return f"{v:.6E}"

def _vals(obj):
    """从 JSON scalar/array 对象提取值列表"""
    if obj["type"] == "scalar":
        return [obj["value"]]
    return obj["values"]

def _repeat_compress(vals):
    """
    把数值列表压缩为 Petrel 的 N*value 格式字符串。
    例：[0.3, 0.3, 0.3] → '3*0.3'
        [0.3, 0.5, 0.5] → '0.3 2*0.5'
    """
    if not vals:
        return ""
    parts = []
    i = 0
    while i < len(vals):
        v = vals[i]
        j = i + 1
        while j < len(vals) and vals[j] == v:
            j += 1
        count = j - i
        fv = _fmt(v)
        parts.append(f"{count}*{fv}" if count > 1 else fv)
        i = j
    return "  ".join(parts)

# ── 主生成器 ──────────────────────────────────────────────────────────────────

class PetrelGenerator:
    def __init__(self, data):
        self.d = data
        self.lines = []

    def _w(self, line=""):
        self.lines.append(line)

    def _comment(self, text):
        self._w(f"-- {text}")

    def _section(self, name, desc=""):
        self._w()
        self._w(f"{name}  {'='*max(1,72-len(name))}")
        if desc:
            self._comment(desc)
        self._w()

    def _write_array(self, kw, obj):
        """
        生成 Petrel 数组关键字：
          KW
            N*val  val  ... /
        """
        vals = _vals(obj)
        self._w(kw)
        compressed = _repeat_compress(vals)
        self._w(f"  {compressed} /")
        self._w()

    # ── RUNSPEC ──────────────────────────────────────────────────────────────

    def _gen_runspec(self):
        self._w("------------------------------------------------------------------------")
        src = self.d["meta"].get("source_file","unknown")
        ts  = self.d["meta"].get("conversion_timestamp","")[:10]
        self._comment(f"Generated by petrel_generator.py from: {src}  ({ts})")
        self._comment("Universal Data Adapter (UDA) Middle Layer")
        self._w("------------------------------------------------------------------------")
        self._w()

        self._w("RUNSPEC")
        self._w()

        # 单位制
        us = self.d["meta"].get("unit_system","field").upper()
        self._w(us)
        self._w()

        # 网格维度
        g = self.d.get("grid", {})
        ni = g.get("ni", 1)
        nj = g.get("nj", 1)
        nk = g.get("nk", 1)
        self._comment("Grid dimensions: NI NJ NK")
        self._w("DIMENS")
        self._w(f"   {ni}   {nj}    {nk}  /")
        self._w()

        # 流体系统声明
        self._w("OIL")
        self._w()
        self._w("WATER")
        self._w()
        self._w("GAS")
        self._w()
        self._w("DISGAS")
        self._w()

        # 起始日期
        start = self.d["meta"].get("start_date")
        if start:
            # start_date 格式为 YYYY-MM-DD
            try:
                yr, mo, dy = start.split("-")
                month_names = ["","JAN","FEB","MAR","APR","MAY","JUN",
                               "JUL","AUG","SEP","OCT","NOV","DEC"]
                mon_str = month_names[int(mo)]
                self._comment("Simulation start date")
                self._w("START")
                self._w(f"  {int(dy)} '{mon_str}' {yr}  /")
                self._w()
            except (ValueError, IndexError):
                pass

        # 井表维度（简单默认值）
        wells = self.d.get("wells", [])
        nwells = max(len(wells), 2)
        self._comment("Well dimensions: NWELLS NCONN NGRPS NWLISTS")
        self._w("WELLDIMS")
        self._w(f"    {nwells}    10    1    {nwells} /")
        self._w()

    # ── GRID ─────────────────────────────────────────────────────────────────

    def _gen_grid(self):
        g = self.d.get("grid", {})
        r = self.d.get("reservoir", {})
        if not g and not r:
            return

        self._section("GRID", "Grid geometry and rock properties")

        # DX / DY / DZ
        for key, kw, desc in [
            ("di","DX","X-direction cell sizes (ft)"),
            ("dj","DY","Y-direction cell sizes (ft)"),
            ("dk","DZ","Z-direction cell thicknesses (ft)"),
        ]:
            obj = g.get(key)
            if obj:
                self._comment(desc)
                self._write_array(kw, obj)

        # TOPS（顶深）
        tops = g.get("tops_ref") or g.get("depth_ref_block")
        if tops:
            if isinstance(tops, dict) and tops.get("type") == "scalar":
                self._comment("Top depths (ft)")
                self._w("TOPS")
                self._w(f"  {_fmt(tops['value'])} /")
                self._w()

        # 岩石属性
        for key, kw, desc in [
            ("porosity","PORO","Porosity (fraction)"),
            ("perm_i","PERMX","X-direction permeability (md)"),
            ("perm_j","PERMY","Y-direction permeability (md)"),
            ("perm_k","PERMZ","Z-direction permeability (md)"),
        ]:
            obj = r.get(key)
            if obj:
                self._comment(desc)
                self._write_array(kw, obj)

    # ── PROPS ────────────────────────────────────────────────────────────────

    def _gen_props(self):
        f  = self.d.get("fluid", {})
        rf = self.d.get("rockfluid", {})
        r  = self.d.get("reservoir", {})
        if not f and not rf:
            return

        self._section("PROPS", "Fluid and rock-fluid properties")

        # ROCK
        rock_pres = r.get("rock_ref_pressure")
        rock_comp = r.get("rock_compressibility")
        if rock_pres and rock_comp:
            self._comment("Rock compressibility: REF_PRES  COMPRESSIBILITY")
            self._w("ROCK")
            self._w(f"   {_fmt(rock_pres['value'])}   {_fmt(rock_comp['value'])}  /")
            self._w()

        # DENSITY
        oil_den  = f.get("oil_density")
        wat_den  = f.get("water_density")
        gas_den  = f.get("gas_density")
        if oil_den or wat_den or gas_den:
            self._comment("Surface densities: OIL  WATER  GAS  (lb/ft3 or kg/m3)")
            self._w("DENSITY")
            od = _fmt(oil_den["value"]) if oil_den else "0"
            wd = _fmt(wat_den["value"]) if wat_den else "0"
            gd = _fmt(gas_den["value"]) if gas_den else "0"
            self._w(f"   {od}   {wd}   {gd}  /")
            self._w()

        # PVTW
        wref = f.get("water_ref_pressure")
        wfvf = f.get("water_fvf")
        wcw  = f.get("water_compressibility")
        wvis = f.get("water_viscosity")
        wcvw = f.get("water_viscosity_coeff")
        if wref and wfvf and wcw and wvis:
            self._comment("Water PVT: REF_PRES  BWI  CW  VWI  CVW")
            self._w("PVTW")
            line = f"   {_fmt(wref['value'])}   {_fmt(wfvf['value'])}   {_fmt(wcw['value'])}   {_fmt(wvis['value'])}"
            if wcvw:
                line += f"   {_fmt(wcvw['value'])}"
            else:
                line += "   0"
            line += "  /"
            self._w(line)
            self._w()

        # PVTO（活油）
        pvto = f.get("pvto_table")
        if pvto:
            self._comment("Live oil PVT: RS  PSAT  BO  VISO (per RS group, / terminates group)")
            self._comment("-- RS      PRES    BO    VISO")
            self._w("PVTO")
            rows = pvto["rows"]
            i = 0
            while i < len(rows):
                rs = rows[i][0]
                # 找连续相同 RS 的行（同一 RS 组）
                j = i
                while j < len(rows) and rows[j][0] == rs:
                    j += 1
                group = rows[i:j]
                # 第一行（饱和点）：带 RS
                first = group[0]
                if len(group) == 1:
                    self._w(f"   {_fmt(first[0])}   {_fmt(first[1])}   {_fmt(first[2])}   {_fmt(first[3])}  /")
                else:
                    # 饱和点行（不带 /）
                    self._w(f"   {_fmt(first[0])}   {_fmt(first[1])}   {_fmt(first[2])}   {_fmt(first[3])}")
                    # 欠饱和行（带空格对齐）
                    for k, row in enumerate(group[1:]):
                        suffix = "  /" if k == len(group)-2 else ""
                        self._w(f"           {_fmt(row[1])}   {_fmt(row[2])}   {_fmt(row[3])}{suffix}")
                i = j
            self._w("/")
            self._w()

        # CMG 来源文件的黑油 PVT（6列：p/rs/bo/eg/viso/visg）→ 转换为 PVTO + PVDG
        cmg_pvt = f.get("pvt_table")
        if cmg_pvt and not pvto:
            self._comment("Oil PVT (from CMG IMEX 6-column table, converted to PVTO format)")
            self._comment("-- RS      PRES    BO    VISO")
            self._w("PVTO")
            for row in cmg_pvt["rows"]:
                # CMG 列：p, rs, bo, eg, viso, visg
                # PVTO 格式：rs  p  bo  viso
                if len(row) >= 5:
                    rs   = row[1]
                    pres = row[0]
                    bo   = row[2]
                    viso = row[4]
                    self._w(f"   {_fmt(rs)}   {_fmt(pres)}   {_fmt(bo)}   {_fmt(viso)}  /")
            self._w("/")
            self._w()

            # PVDG（从 CMG 6列的 eg/visg 提取）
            self._comment("Dry gas PVT (from CMG table): PGAS  BG  VISGAS")
            self._w("PVDG")
            for row in cmg_pvt["rows"]:
                if len(row) >= 6:
                    pres = row[0]
                    eg   = row[3]
                    visg = row[5]
                    self._w(f"   {_fmt(pres)}   {_fmt(eg)}   {_fmt(visg)}")
            self._w("/")
            self._w()

        # PVDG（直接来自 Petrel 文件）
        pvdg = f.get("pvdg_table")
        if pvdg:
            self._comment("Dry gas PVT: PGAS  BG  VISGAS")
            self._w("PVDG")
            for row in pvdg["rows"]:
                self._w(f"   {_fmt(row[0])}   {_fmt(row[1])}   {_fmt(row[2])}")
            self._w("/")
            self._w()

        # ── 相渗表 ──

        # SWOF（来自 CMG *SWT 或 Petrel SWOF）
        swt = rf.get("swt_table")
        if swt:
            cols = swt["columns"]
            if "krow" in cols:
                self._comment("Water-oil relative permeability: Sw  KRW  KROW  PCOW")
                self._w("SWOF")
                for row in swt["rows"]:
                    pcow = _fmt(row[3]) if len(row) >= 4 else "0"
                    self._w(f"   {_fmt(row[0])}   {_fmt(row[1])}   {_fmt(row[2])}   {pcow}")
                self._w("/")
                self._w()

        # SGOF（来自 CMG *SLT 或 Petrel SGOF）
        slt = rf.get("slt_table")
        if slt:
            cols = slt["columns"]
            self._comment("Gas-oil relative permeability: Sg  KRG  KROG  PCOG")
            self._w("SGOF")
            for row in slt["rows"]:
                pcog = _fmt(row[3]) if len(row) >= 4 else "0"
                col3 = _fmt(row[2]) if len(row) >= 3 else "0"
                self._w(f"   {_fmt(row[0])}   {_fmt(row[1])}   {col3}   {pcog}")
            self._w("/")
            self._w()

        # SWFN（三函数相渗，Petrel SWFN/SGFN/SOF3 体系）
        swfn = rf.get("swfn_table")
        sgfn = rf.get("sgfn_table")
        sof3 = rf.get("sof3_table")

        if swfn:
            self._comment("Water relative permeability: Sw  KRW  PCOW")
            self._w("SWFN")
            for row in swfn["rows"]:
                pcow = _fmt(row[2]) if len(row) >= 3 else "0"
                self._w(f"   {_fmt(row[0])}   {_fmt(row[1])}   {pcow}")
            self._w("/")
            self._w()

        if sgfn:
            self._comment("Gas relative permeability: Sg  KRG  PCOG")
            self._w("SGFN")
            for row in sgfn["rows"]:
                pcog = _fmt(row[2]) if len(row) >= 3 else "0"
                self._w(f"   {_fmt(row[0])}   {_fmt(row[1])}   {pcog}")
            self._w("/")
            self._w()

        if sof3:
            self._comment("Oil relative permeability: So  KROW  KROG")
            self._w("SOF3")
            for row in sof3["rows"]:
                krog = _fmt(row[2]) if len(row) >= 3 else "0"
                self._w(f"   {_fmt(row[0])}   {_fmt(row[1])}   {krog}")
            self._w("/")
            self._w()

    # ── SOLUTION ─────────────────────────────────────────────────────────────

    def _gen_solution(self):
        ini = self.d.get("initial", {})
        if not ini:
            return

        self._section("SOLUTION", "Initial conditions")

        ref_depth = ini.get("ref_depth")
        ref_pres  = ini.get("ref_pressure")
        woc       = ini.get("woc_depth")
        goc       = ini.get("goc_depth")

        if ref_depth and ref_pres:
            self._comment("Equilibration data:")
            self._comment("  DATUM_DEPTH  DATUM_PRES  OWC_DEPTH  PCWOC  GOC_DEPTH  PCGOC  RSVD  RVVD  SOLN")
            self._w("EQUIL")
            woc_v = _fmt(woc["value"]) if woc else _fmt(ref_depth["value"] + 500)
            goc_v = _fmt(goc["value"]) if goc else _fmt(ref_depth["value"] - 500)
            self._w(f"   {_fmt(ref_depth['value'])}   {_fmt(ref_pres['value'])}"
                    f"   {woc_v}   0   {goc_v}   0   1   0   0  /")
            self._w()

        # RSVD 初始溶解气油比
        rsvd = ini.get("rsvd_table")
        if rsvd:
            self._comment("Initial RS vs depth: DEPTH  RS")
            self._w("RSVD")
            for row in rsvd["rows"]:
                self._w(f"   {_fmt(row[0])}   {_fmt(row[1])}")
            self._w("/")
            self._w()

    # ── SCHEDULE ─────────────────────────────────────────────────────────────

    def _gen_schedule(self):
        wells = self.d.get("wells", [])
        if not wells:
            return

        self._section("SCHEDULE", "Well operations and time stepping")

        # 区分生产井和注入井
        producers = [w for w in wells if w.get("well_type") == "PRODUCER"]
        injectors = [w for w in wells if w.get("well_type") == "INJECTOR"]

        # WELSPECS
        self._comment("Well specification data:")
        self._comment("  WELL_NAME  GROUP  I  J  REF_DEPTH  PHASE")
        self._w("WELSPECS")
        ref_depth = self.d.get("initial", {}).get("ref_depth", {})
        rdv = _fmt(ref_depth.get("value", 0)) if ref_depth else "1*"
        for w in wells:
            name  = w.get("well_name", "WELL")
            group = w.get("well_group", "FIELD")
            wi    = w.get("well_i", 1)
            wj    = w.get("well_j", 1)
            phase = w.get("phase", "OIL")
            # 如果原始文件没存 well_i/j，从射孔推断
            perfs = w.get("perforations", [])
            if perfs and wi == 1:
                wi = perfs[0]["i"]
                wj = perfs[0]["j"]
            if not phase or phase == "None":
                phase = "GAS" if w.get("well_type") == "INJECTOR" else "OIL"
            self._w(f"    '{name}'  '{group}'   {wi}  {wj}   {rdv}  '{phase}'  /")
        self._w("/")
        self._w()

        # COMPDAT
        self._comment("Completion specification data:")
        self._comment("  WELL_NAME  I  J  K1  K2  OPEN/SHUT  SAT  CF  DIAM")
        self._w("COMPDAT")
        for w in wells:
            name   = w.get("well_name","WELL")
            radius = w.get("well_radius")
            diam   = _fmt(radius * 2) if radius else "0.5"
            for p in w.get("perforations", []):
                status = p.get("status","OPEN").upper()
                self._w(f"    '{name}'  {p['i']}  {p['j']}  {p['k']}  {p['k']}"
                        f"  '{status}'  1*  1*  {diam}  /")
        self._w("/")
        self._w()

        # WCONPROD
        if producers:
            self._comment("Production well controls:")
            self._comment("  WELL_NAME  OPEN/SHUT  MODE  OIL_RATE  WATER_RATE  GAS_RATE  LIQU  RES  BHP")
            self._w("WCONPROD")
            for w in producers:
                name     = w.get("well_name","WELL")
                oil_rate = w.get("rate_max")
                bhp      = w.get("bhp_min")
                oil_str  = _fmt(oil_rate) if oil_rate is not None else "1*"
                bhp_str  = _fmt(bhp) if bhp is not None else "1*"
                self._w(f"    '{name}'  'OPEN'  'ORAT'  {oil_str}  4*  {bhp_str}  /")
            self._w("/")
            self._w()

        # WCONINJE
        if injectors:
            self._comment("Injection well controls:")
            self._comment("  WELL_NAME  INJ_TYPE  OPEN/SHUT  MODE  RATE  RESV  BHP")
            self._w("WCONINJE")
            for w in injectors:
                name     = w.get("well_name","WELL")
                inj_type = w.get("inj_fluid") or w.get("phase","GAS")
                if not inj_type or inj_type == "None":
                    inj_type = "GAS"
                rate     = w.get("rate_max")
                bhp      = w.get("bhp_max")
                rate_str = _fmt(rate) if rate is not None else "1*"
                bhp_str  = _fmt(bhp) if bhp is not None else "1*"
                self._w(f"    '{name}'  '{inj_type}'  'OPEN'  'RATE'  {rate_str}  1*  {bhp_str}  /")
            self._w("/")
            self._w()

        # TSTEP（来自 CMG 的时间步）
        total_time = self.d.get("_total_sim_time")
        if not total_time:
            # 从 wells 的 alter_schedule 推断最大时间
            max_t = 0.0
            for w in wells:
                for a in w.get("alter_schedule", []):
                    max_t = max(max_t, a.get("time", 0.0))
            total_time = max_t if max_t > 0 else 3650.0

        self._comment(f"Time stepping: total {_fmt(total_time)} days")
        self._w("TSTEP")
        # 简单切分：最多100天步长
        remaining = float(total_time)
        step = min(100.0, remaining)
        steps = []
        while remaining > 1e-6:
            s = min(step, remaining)
            steps.append(s)
            remaining -= s
        # 压缩连续相同步长
        self._w("  " + _repeat_compress(steps))
        self._w("/")
        self._w()

        self._w("END  ================================================================")

    # ── 主入口 ───────────────────────────────────────────────────────────────

    def generate(self):
        self._gen_runspec()
        self._gen_grid()
        self._gen_props()
        self._gen_solution()
        self._gen_schedule()
        return "\n".join(self.lines)


def generate_petrel(data, output_path):
    text = PetrelGenerator(data).generate()
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(text)
    return text


if __name__ == "__main__":
    import sys

    default_json = Path("outputs/json/mxspe001_parsed.json")
    json_file = Path(sys.argv[1]) if len(sys.argv) > 1 else default_json

    out_dir = Path("outputs/petrel")
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / f"{json_file.stem.replace('_parsed','')}_converted.DATA"

    with open(json_file, encoding="utf-8") as f:
        data = json.load(f)

    generate_petrel(data, out_file)
    print(f"Generated: {out_file}")
