# =============================================================================
# generators/petrel_generator.py  —  通用 JSON → Petrel Eclipse .DATA
# 架构：规则驱动
#   - generators.petrel 配置决定每个 JSON 字段对应哪个关键字和格式
#   - 新增简单字段：只需在 keyword_registry.yaml 的 generators.petrel 下添加一行
# =============================================================================

import json
import sys
from pathlib import Path
from datetime import datetime

sys.path.insert(0, str(Path(__file__).parent.parent))
from utils.confidence_checks import evaluate_confidence
from utils.pvt_metadata import apply_pvt_role
from utils.rule_loader import get_loader
from utils.reporting import write_report_bundle
from utils.target_preflight import evaluate_target_preflight

# ── 格式化工具 ────────────────────────────────────────────────────────────────

_MONTH_ABB = {1:"JAN",2:"FEB",3:"MAR",4:"APR",5:"MAY",6:"JUN",
              7:"JUL",8:"AUG",9:"SEP",10:"OCT",11:"NOV",12:"DEC"}

def _fmt(v, width=14):
    if isinstance(v, int):
        return str(v).rjust(width)
    if abs(v) >= 1e5 or (abs(v) < 1e-3 and v != 0):
        return f"{v:.6E}".rjust(width)
    return f"{v:.6g}".rjust(width)

def _get_val(obj):
    if obj is None:
        return None
    if isinstance(obj, dict):
        if obj.get("type") == "scalar":
            return obj["value"]
        if obj.get("type") == "array":
            return obj["values"]
    return obj

def _get_modifier(obj):
    if isinstance(obj, dict):
        return obj.get("modifier")
    return None

def _compress_array(vals):
    """将连续相同值压缩为 N*val 格式"""
    if not vals:
        return ""
    parts = []
    i = 0
    while i < len(vals):
        v = vals[i]
        count = 1
        while i + count < len(vals) and vals[i + count] == v:
            count += 1
        if count > 1:
            parts.append(f"{count}*{_fmt(v).strip()}")
        else:
            parts.append(_fmt(v).strip())
        i += count
    # 每行最多 8 个值
    chunks = []
    chunk = []
    for p in parts:
        chunk.append(p)
        if len(chunk) >= 8:
            chunks.append("  " + "  ".join(chunk))
            chunk = []
    if chunk:
        chunks.append("  " + "  ".join(chunk))
    return "\n".join(chunks)

def _write_array_petrel(lines, keyword, obj, trailing_slash=True):
    """写 Petrel 数组：KEYWORD\n  val1 val2 ... /"""
    if obj is None:
        return
    val = _get_val(obj)
    if val is None:
        return
    lines.append(keyword)
    if isinstance(val, list):
        body = _compress_array(val)
        if trailing_slash:
            lines.append(body + "  /")
        else:
            lines.append(body)
    else:
        if trailing_slash:
            lines.append(f"  {_fmt(val).strip()} /")
        else:
            lines.append(f"  {_fmt(val).strip()}")

def _write_table_slash(lines, keyword, tbl, columns=None):
    """写 Petrel 表格：KEYWORD\n  v1 v2 v3 /\n  v1 v2 v3 /\n/"""
    if not tbl or not tbl.get("rows"):
        return
    cols = columns or tbl.get("columns", [])
    lines.append(keyword)
    if cols:
        lines.append("-- " + "  ".join(f"{c:>10}" for c in cols))
    for row in tbl["rows"]:
        lines.append("  " + "  ".join(_fmt(v) for v in row) + "  /")
    lines.append("/")


# ── 主生成器 ──────────────────────────────────────────────────────────────────

class PetrelGenerator:

    def __init__(self):
        self._rl = get_loader()
        self._gen_cfg = self._rl.petrel_gen_config()

    def generate(self, data):
        lines = []
        meta      = data.get("meta", {})
        grid      = data.get("grid", {})
        reservoir = data.get("reservoir", {})
        fluid     = data.get("fluid", {})
        rockfluid = data.get("rockfluid", {})
        initial   = data.get("initial", {})
        numerical = data.get("numerical", {})
        wells     = data.get("wells", [])
        timeline_events = data.get("timeline_events", [])

        lines += [
            f"-- Generated by UDA Middle Layer",
            f"-- Source: {meta.get('source_file', 'unknown')}",
            f"-- Date:   {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "",
        ]

        self._write_runspec(lines, meta, grid, wells)
        self._write_grid_section(lines, grid, reservoir)
        self._write_props(lines, fluid, rockfluid)
        self._write_solution(lines, initial)
        self._write_summary(lines)
        self._write_schedule(lines, wells, meta, timeline_events)
        self._write_unparsed_blocks(lines, data.get("unparsed_blocks", []))
        lines.append("END")
        return "\n".join(lines) + "\n"

    # ── RUNSPEC ───────────────────────────────────────────────────────────────

    def _write_runspec(self, lines, meta, grid, wells):
        lines += ["RUNSPEC", ""]
        start = meta.get("start_date", "")
        if start:
            parts = start.split("-")
            if len(parts) == 3:
                mon_str = _MONTH_ABB.get(int(parts[1]), "JAN")
                lines.append(f"START")
                lines.append(f"  {int(parts[2])} '{mon_str}' {parts[0]} /")
                lines.append("")

        ni = grid.get("ni", 1)
        nj = grid.get("nj", 1)
        nk = grid.get("nk", 1)
        lines += [
            f"DIMENS",
            f"  {ni}  {nj}  {nk} /",
            "",
            "OIL", "WATER", "GAS", "DISGAS",
            "",
        ]
        unit = meta.get("unit_system", "field").upper()
        lines += [unit, ""]

        # 井维度
        nwells = max(len(wells), 1)
        nconns = sum(len(w.get("perforations", [])) for w in wells) or nk
        lines += [
            "WELLDIMS",
            f"  {nwells}  {nconns}  1  {nwells} /",
            "",
            "TABDIMS",
            "  1 /",
            "",
        ]

    # ── GRID ─────────────────────────────────────────────────────────────────

    def _write_grid_section(self, lines, grid, reservoir):
        lines += ["GRID", ""]

        gt = grid.get("grid_type", "CART").upper()
        if gt == "RADIAL":
            lines.append("RADIAL")
            lines.append("")
            inrad = _get_val(grid.get("inrad"))
            if inrad is not None:
                lines.append(f"INRAD")
                lines.append(f"  {_fmt(inrad).strip()} /")
                lines.append("")
            # DRV → DX, DTHETA → DY, DK → DZ
            drv_obj = grid.get("di") or grid.get("drv")
            if drv_obj:
                _write_array_petrel(lines, "DRV", drv_obj)
                lines.append("")
            dtheta_obj = grid.get("dj") or grid.get("dtheta")
            if dtheta_obj:
                _write_array_petrel(lines, "DTHETA", dtheta_obj)
                lines.append("")
        else:
            for key, kw in [("di", "DX"), ("dj", "DY"), ("dk", "DZ")]:
                obj = grid.get(key)
                if obj:
                    _write_array_petrel(lines, kw, obj)
                    lines.append("")

        # TOPS
        tops_obj = grid.get("tops_ref")
        depth_block = grid.get("depth_ref_block")
        if tops_obj:
            _write_array_petrel(lines, "TOPS", tops_obj)
            lines.append("")
        elif depth_block and isinstance(depth_block, dict):
            ni = grid.get("ni", 1)
            nj = grid.get("nj", 1)
            nk = grid.get("nk", 1)
            v = depth_block.get("value", 0)
            lines.append("TOPS")
            lines.append(f"  {ni*nj}*{_fmt(v).strip()} /")
            lines.append("")

        # 储层属性（GRID 段）
        cfg_grid_res = {
            "porosity": "PORO",
            "perm_i":   "PERMX",
            "perm_j":   "PERMY",
            "perm_k":   "PERMZ",
            "ntg":      "NTG",
        }
        for key, kw in cfg_grid_res.items():
            obj = reservoir.get(key)
            if obj:
                _write_array_petrel(lines, kw, obj)
                lines.append("")

    # ── PROPS ─────────────────────────────────────────────────────────────────

    def _write_props(self, lines, fluid, rockfluid):
        lines += ["PROPS", ""]

        # PVTW
        pvtw_fields = [
            fluid.get("water_ref_pressure"),
            fluid.get("water_fvf"),
            fluid.get("water_compressibility"),
            fluid.get("water_viscosity"),
            fluid.get("water_viscosity_coeff"),
        ]
        pvtw_vals = [_get_val(f) for f in pvtw_fields]
        if any(v is not None for v in pvtw_vals):
            lines.append("PVTW")
            row = "  " + "  ".join(
                _fmt(v).strip() if v is not None else "1*"
                for v in pvtw_vals
            ) + " /"
            lines.append(row)
            lines.append("")

        # DENSITY
        od = _get_val(fluid.get("oil_density"))
        wd = _get_val(fluid.get("water_density"))
        gd = _get_val(fluid.get("gas_density"))
        if any(v is not None for v in [od, wd, gd]):
            lines.append("DENSITY")
            row = "  " + "  ".join(
                _fmt(v).strip() if v is not None else "1*"
                for v in [od, wd, gd]
            ) + " /"
            lines.append(row)
            lines.append("")

        # ROCK
        rp = _get_val(fluid.get("rock_ref_pressure") or
                      fluid.get("reservoir", {}).get("rock_ref_pressure"))
        rc = _get_val(fluid.get("rock_compressibility") or
                      fluid.get("reservoir", {}).get("rock_compressibility"))
        # rock 也可能在 reservoir 节点，兼容两种来源
        if rp is None:
            # 尝试从外层 data["reservoir"] 拿（generator 调用时已拆分）
            pass
        if rp is not None and rc is not None:
            lines.append("ROCK")
            lines.append(f"  {_fmt(rp).strip()}  {_fmt(rc).strip()} /")
            lines.append("")

        # PVTO
        pvto = fluid.get("pvto_table")
        if not pvto and fluid.get("pvt_table"):
            # CMG来源的 pvt_table → 拆分回 PVTO/PVDG
            pvto, pvdg = self._split_pvt_to_pvto_pvdg(fluid["pvt_table"])
            if pvto:
                _write_table_slash(lines, "PVTO", pvto, ["rs", "p", "bo", "viso"])
                lines.append("")
            if pvdg:
                _write_table_slash(lines, "PVDG", pvdg, ["p", "bg", "visg"])
                lines.append("")
        else:
            if pvto:
                _write_table_slash(lines, "PVTO", pvto, ["rs", "p", "bo", "viso"])
                lines.append("")
            pvdg = fluid.get("pvdg_table")
            if pvdg:
                _write_table_slash(lines, "PVDG", pvdg, ["p", "bg", "visg"])
                lines.append("")

        # 相渗表：按优先级写，保留原始格式
        self._write_rockfluid(lines, rockfluid)

    def _split_pvt_to_pvto_pvdg(self, pvt6):
        """
        CMG 6列 pvt_table (p,rs,bo,eg,viso,visg) → PVTO + PVDG
        """
        rows6 = pvt6["rows"]  # [p, rs, bo, eg, viso, visg]
        pvto_rows = [[r[1], r[0], r[2], r[4]] for r in rows6]  # rs,p,bo,viso
        pvdg_rows = [[r[0], 1.0/r[3] if r[3] > 0 else 0.0, r[5]] for r in rows6]  # p,bg,visg
        pvto = apply_pvt_role(
            {"type": "table", "columns": ["rs","p","bo","viso"],
             "rows": pvto_rows, "confidence": 0.9, "source": "split from pvt_table"},
            pvt_form="eclipse_pvto",
            representation_role="derived_for_petrel",
            preferred_backend="petrel",
            derived_from=["fluid.pvt_table"],
        )
        pvdg = apply_pvt_role(
            {"type": "table", "columns": ["p","bg","visg"],
             "rows": pvdg_rows, "confidence": 0.9, "source": "split from pvt_table"},
            pvt_form="eclipse_pvdg",
            representation_role="derived_for_petrel",
            preferred_backend="petrel",
            derived_from=["fluid.pvt_table"],
        )
        return pvto, pvdg

    def _write_rockfluid(self, lines, rockfluid):
        """按优先级写相渗表，保留原始三表或两表格式"""
        cfg = self._gen_cfg.get("rockfluid", {})

        # 优先级：已有的原始表 > 需要转换的表
        wrote = False
        for key, field_cfg in cfg.items():
            tbl = rockfluid.get(key)
            if not tbl or not tbl.get("rows"):
                continue
            kw = field_cfg.get("keyword")
            cols = field_cfg.get("columns")
            if kw and cols:
                _write_table_slash(lines, kw, tbl, cols)
                lines.append("")
                wrote = True

        if not wrote:
            # 没有相渗表，写一个占位注释
            lines.append("-- ** WARNING: No rock-fluid tables found in JSON **")

    # ── SOLUTION ──────────────────────────────────────────────────────────────

    def _write_solution(self, lines, initial):
        lines += ["SOLUTION", ""]
        # EQUIL
        ref_depth = _get_val(initial.get("ref_depth"))
        ref_pres  = _get_val(initial.get("ref_pressure"))
        woc       = _get_val(initial.get("woc_depth"))
        goc       = _get_val(initial.get("goc_depth"))
        if ref_depth is not None and ref_pres is not None:
            woc_str = _fmt(woc).strip() if woc is not None else "0"
            goc_str = _fmt(goc).strip() if goc is not None else "0"
            lines.append("EQUIL")
            lines.append(f"  {_fmt(ref_depth).strip()}  {_fmt(ref_pres).strip()}  "
                         f"{woc_str}  0  {goc_str}  0 /")
            lines.append("")
        # RSVD
        rsvd = initial.get("rsvd_table")
        if rsvd and rsvd.get("rows"):
            lines.append("RSVD")
            for row in rsvd["rows"]:
                lines.append("  " + "  ".join(_fmt(v) for v in row))
            lines.append("/")
            lines.append("")
        # PBVD
        pbvd = initial.get("pbvd_table")
        if pbvd and pbvd.get("rows"):
            lines.append("PBVD")
            for row in pbvd["rows"]:
                lines.append("  " + "  ".join(_fmt(v) for v in row))
            lines.append("/")
            lines.append("")

    # ── SUMMARY ───────────────────────────────────────────────────────────────

    def _write_summary(self, lines):
        lines += [
            "SUMMARY",
            "",
            "ALL",
            "WBHP",
            "WGOR",
            "",
        ]

    # ── SCHEDULE ──────────────────────────────────────────────────────────────

    def _write_schedule(self, lines, wells, meta, timeline_events):
        lines += ["SCHEDULE", ""]

        # WELSPECS
        if wells:
            lines.append("WELSPECS")
            lines.append("-- Name   Group  I   J   RefDepth  Phase")
            for w in wells:
                name  = w.get("well_name", "W1")
                group = w.get("well_group", "FIELD")
                ci    = w.get("well_i", 1)
                cj    = w.get("well_j", 1)
                phase = w.get("phase", "OIL").upper()
                if w.get("well_type", "").upper() == "INJECTOR":
                    phase = w.get("inj_fluid", "GAS") or "GAS"
                lines.append(f"  '{name}'  '{group}'  {ci}  {cj}  1*  {phase} /")
            lines.append("/")
            lines.append("")

        # COMPDAT
        if wells:
            lines.append("COMPDAT")
            lines.append("-- Name  I  J  K1 K2  Status  Sat  Trans  Diam")
            for w in wells:
                name   = w.get("well_name", "W1")
                radius = w.get("well_radius")
                diam   = (radius * 2.0) if radius else 0.1524
                for p in w.get("perforations", []):
                    status = p.get("status", "OPEN")
                    lines.append(f"  '{name}'  {p['i']}  {p['j']}  {p['k']}  {p['k']}"
                                 f"  {status}  1*  1*  {diam:.4f} /")
            lines.append("/")
            lines.append("")

        # WCONINJE / WCONPROD
        inj_wells  = [w for w in wells if w.get("well_type","").upper() == "INJECTOR"]
        prod_wells = [w for w in wells if w.get("well_type","").upper() != "INJECTOR"]

        if inj_wells:
            lines.append("WCONINJE")
            lines.append("-- Name  Type  Status  Mode  Rate  Resv  BHP")
            for w in inj_wells:
                name     = w.get("well_name","W1")
                inj_type = (w.get("inj_fluid") or "GAS").upper()
                rate     = w.get("rate_max")
                bhp      = w.get("bhp_max")
                rate_str = _fmt(rate).strip() if rate else "1*"
                bhp_str  = _fmt(bhp).strip() if bhp else "1*"
                lines.append(f"  '{name}'  {inj_type}  OPEN  RATE  {rate_str}  1*  {bhp_str} /")
            lines.append("/")
            lines.append("")

        if prod_wells:
            lines.append("WCONPROD")
            lines.append("-- Name  Status  Mode  Oil  Water  Gas  Liq  Resv  BHP")
            for w in prod_wells:
                name    = w.get("well_name","W1")
                rate    = w.get("rate_max")
                bhp     = w.get("bhp_min")
                rate_str = _fmt(rate).strip() if rate else "1*"
                bhp_str  = _fmt(bhp).strip() if bhp else "1*"
                lines.append(f"  '{name}'  OPEN  ORAT  {rate_str}  1*  1*  1*  1*  {bhp_str} /")
            lines.append("/")
            lines.append("")

        # TSTEP / WELTARG
        self._write_dynamic(lines, meta, timeline_events)

    def _write_dynamic(self, lines, meta, timeline_events):
        """将 absolute_days 事件转为 TSTEP + WELTARG 块"""
        events = [
            ev for ev in timeline_events
            if ev.get("event_type") == "WELL_TARGET_CHANGE"
        ]
        if not events:
            total = meta.get("_total_sim_time", 0.0)
            if total and total > 0:
                lines.append("TSTEP")
                lines.append(f"  {total:.1f} /")
                lines.append("")
            return

        events.sort(key=lambda e: float(e.get("absolute_days", 0.0)))
        prev_time = 0.0
        from itertools import groupby

        for t, group in groupby(events, key=lambda e: float(e.get("absolute_days", 0.0))):
            group = list(group)
            dt = t - prev_time
            if dt > 0:
                lines.append("TSTEP")
                lines.append(f"  {dt:.2f} /")
                lines.append("")
            for ev in group:
                name = ev.get("well_name", "W1")
                target = ev.get("target", "ORATE")
                val = ev.get("value", 0.0)
                lines.append("WELTARG")
                lines.append(f"  '{name}'  {target}  {_fmt(val).strip()} /")
                lines.append("/")
                lines.append("")
            prev_time = t

        total = meta.get("_total_sim_time", prev_time)
        if total > prev_time:
            lines.append("TSTEP")
            lines.append(f"  {total - prev_time:.2f} /")
            lines.append("")

    def _write_unparsed_blocks(self, lines, unparsed_blocks):
        if not unparsed_blocks:
            return
        lines.append("-- ── UNPARSED BLOCKS ──")
        for blk in unparsed_blocks:
            ln = blk.get("line", "?")
            txt = str(blk.get("text", "")).strip()
            lines.append(f"-- ** UNPARSED [line {ln}]: {txt}")



# ── 对外接口 ──────────────────────────────────────────────────────────────────

def generate_petrel(data_or_json, output_file=None, report_dir="outputs/reports/generators"):
    source_name = str(data_or_json) if isinstance(data_or_json, (str, Path)) else "in_memory_json"
    if isinstance(data_or_json, (str, Path)):
        with open(data_or_json, encoding="utf-8") as f:
            data = json.load(f)
    else:
        data = data_or_json

    # ROCK ??? reservoir ???? generator ??? fluid ??? PROPS
    data = dict(data)
    res = data.get("reservoir", {})
    fl = dict(data.get("fluid", {}))
    if not fl.get("rock_ref_pressure") and res.get("rock_ref_pressure"):
        fl["rock_ref_pressure"] = res["rock_ref_pressure"]
    if not fl.get("rock_compressibility") and res.get("rock_compressibility"):
        fl["rock_compressibility"] = res["rock_compressibility"]
    data["fluid"] = fl

    def _write_failed_report(errors, warnings=None):
        md_path, json_path = write_report_bundle(
            report_dir=report_dir,
            source_name=Path(source_name).name,
            report_type="generate_petrel",
            title="Petrel generation report",
            summary_items=[
                ("output_file", "(not written)"),
                ("line_count", 0),
                ("well_count", len(data.get("wells", []))),
                ("grid_type", data.get("grid", {}).get("grid_type", "unknown")),
            ],
            warnings=warnings or [],
            errors=errors,
            details={
                "stage": "pre_generation_validation",
                "preflight": preflight,
                "confidence_check": confidence_check,
            },
        )
        data.setdefault("_generate_report", {"md": str(md_path), "json": str(json_path)})

    preflight = evaluate_target_preflight(data, target="petrel")
    confidence_check = evaluate_confidence(data, target="petrel")
    if preflight["blockers"]:
        _write_failed_report(preflight["blockers"], warnings=preflight["warnings"])
        raise ValueError(
            "Petrel generation blocked by preflight checks: "
            + "; ".join(preflight["blockers"])
        )
    if confidence_check["blockers"]:
        _write_failed_report(confidence_check["blockers"], warnings=preflight["warnings"] + confidence_check["warnings"])
        raise ValueError(
            "Petrel generation blocked by very low-confidence critical fields: "
            + "; ".join(confidence_check["blockers"])
        )

    content = PetrelGenerator().generate(data)

    out_path = None
    if output_file:
        out_path = Path(output_file)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(content)

    warnings = []
    if not data.get("wells"):
        warnings.append("no wells found; SCHEDULE may contain only static content")
    warnings.extend(f"preflight: {w}" for w in preflight["warnings"][:10])
    if len(preflight["warnings"]) > 10:
        warnings.append(f"preflight: omitted {len(preflight['warnings']) - 10} more items")
    warnings.extend(f"low confidence: {w}" for w in confidence_check["warnings"][:10])
    if len(confidence_check["warnings"]) > 10:
        warnings.append(f"low confidence: omitted {len(confidence_check['warnings']) - 10} more items")

    summary = [
        ("output_file", str(out_path) if out_path else "(not written)"),
        ("line_count", len(content.splitlines())),
        ("well_count", len(data.get("wells", []))),
        ("grid_type", data.get("grid", {}).get("grid_type", "CART")),
    ]
    md_path, json_path = write_report_bundle(
        report_dir=report_dir,
        source_name=Path(source_name).name,
        report_type="generate_petrel",
        title="Petrel generation report",
        summary_items=summary,
        warnings=warnings,
        errors=[],
        details={
            "has_swof": bool(data.get("rockfluid", {}).get("swof_table")),
            "has_sgof": bool(data.get("rockfluid", {}).get("sgof_table")),
            "has_swt": bool(data.get("rockfluid", {}).get("swt_table")),
            "has_slt": bool(data.get("rockfluid", {}).get("slt_table")),
            "preflight": preflight,
            "confidence_check": confidence_check,
        },
    )
    data.setdefault("_generate_report", {"md": str(md_path), "json": str(json_path)})

    return content


if __name__ == "__main__":
    default_json = Path("outputs/json/mxspe001_parsed.json")
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else default_json

    out_dir = Path("outputs/petrel")
    out_dir.mkdir(parents=True, exist_ok=True)
    stem = Path(src).stem.replace("_parsed", "")
    out = out_dir / f"{stem}_converted.DATA"

    generate_petrel(src, str(out))
    print(f"Petrel file written: {out}")
